(define (problem hanoi-3discs) (:domain hanoi)
    (:objects disc2 disc3 - disc)
    (:init
        (smaller disc1 peg1)
        (smaller disc1 peg2)
        (smaller disc1 peg3)
        (smaller disc2 peg1)
        (smaller disc2 peg2)
        (smaller disc2 peg3)
        (smaller disc3 peg1)
        (smaller disc3 peg2)
        (smaller disc3 peg3)
        (smaller disc1 disc2)
        (smaller disc1 disc3)
        (smaller disc2 disc3)
        (clear peg2)
        (clear peg3)
        (clear disc1)
        (on disc1 disc2)
        (on disc2 disc3)
        (on disc3 peg1)
    )
    (:goal (and
        (on disc1 disc2)
        (on disc2 disc3)
        (on disc3 peg3)
    ))
)
